### ISSUE TITLE
compile error ubuntu 16.04 -- g++ 5.4.0

### ISSUE THREAD

**Issue by hamnaz** [JeanLucPons/VanitySearch#8]
make gpu=1 all
mkdir -p obj
cd obj &&       mkdir -p GPU
cd obj &&       mkdir -p hash
g++ -DWITHGPU -m64  -Wno-write-strings -O2 -I. -I/usr/local/cuda-8.0/include -o obj/Base58.o -c Base58.cpp
Base58.cpp: In function ‘bool DecodeBase58(const char*, std::vector<unsigned char>&)’:
Base58.cpp:45:19: error: ‘nullptr’ was not declared in this scope
         if (ch == nullptr)
                   ^
Base58.cpp: In function ‘std::__cxx11::string EncodeBase58(const unsigned char*, const unsigned char*)’:
Base58.cpp:90:5: error: ‘uint32_t’ was not declared in this scope
     uint32_t carry = pbegin[i];
     ^
Base58.cpp:92:7: error: ‘carry’ was not declared in this scope
       carry += (uint32_t)(digits[j]) << 8;
       ^
Base58.cpp:96:11: error: ‘carry’ was not declared in this scope
     while(carry > 0) {
           ^
Makefile:56: recipe for target 'obj/Base58.o' failed
make: *** [obj/Base58.o] Error 1
chawla@i3-6100:~/van/VanitySearch$ make all
cd obj &&       mkdir -p GPU
g++ -m64 -msse -Wno-write-strings -O2 -I. -I/usr/local/cuda-8.0/include -o obj/Base58.o -c Base58.cpp
Base58.cpp: In function ‘bool DecodeBase58(const char*, std::vector<unsigned char>&)’:
Base58.cpp:45:19: error: ‘nullptr’ was not declared in this scope
         if (ch == nullptr)
                   ^
Base58.cpp: In function ‘std::__cxx11::string EncodeBase58(const unsigned char*, const unsigned char*)’:
Base58.cpp:90:5: error: ‘uint32_t’ was not declared in this scope
     uint32_t carry = pbegin[i];
     ^
Base58.cpp:92:7: error: ‘carry’ was not declared in this scope
       carry += (uint32_t)(digits[j]) << 8;
       ^
Base58.cpp:96:11: error: ‘carry’ was not declared in this scope
     while(carry > 0) {
           ^
Makefile:56: recipe for target 'obj/Base58.o' failed
make: *** [obj/Base58.o] Error 1

**Comment by hamnaz** [comment]
![error](https://user-images.githubusercontent.com/42878992/54088097-dda30e80-437b-11e9-8021-56f308a6bbef.jpg)

**Comment by JeanLucPons** [comment]
Hello,
What is your release of gcc ?

**Comment by hamnaz** [comment]
still error  

chawla@i3-6100:~/van/VanitySearch$ make gpu=1 all
cd obj &&       mkdir -p GPU
g++ -DWITHGPU -m64  -Wno-write-strings -O2 -I. -I/usr/local/cuda-8.0/include -o obj/Base58.o -c Base58.cpp
Base58.cpp: In function ‘bool DecodeBase58(const char*, std::vector<unsigned char>&)’:
Base58.cpp:47:19: error: ‘null’ was not declared in this scope
         if (ch == null)
                   ^
Base58.cpp: In function ‘std::__cxx11::string EncodeBase58(const unsigned char*, const unsigned char*)’:
Base58.cpp:92:5: error: ‘uint32_t’ was not declared in this scope
     uint32_t carry = pbegin[i];
     ^
Base58.cpp:94:7: error: ‘carry’ was not declared in this scope
       carry += (uint32_t)(digits[j]) << 8;
       ^
Base58.cpp:98:11: error: ‘carry’ was not declared in this scope
     while(carry > 0) {
           ^
Makefile:56: recipe for target 'obj/Base58.o' failed
make: *** [obj/Base58.o] Error 1

**Comment by hamnaz** [comment]
chawla@i3-6100:~/van/VanitySearch$ make gpu=1 all
cd obj &&       mkdir -p GPU
g++ -DWITHGPU -m64  -Wno-write-strings -O2 -I. -I/usr/local/cuda-8.0/include -o obj/Base58.o -c Base58.cpp
Base58.cpp: In function ‘std::__cxx11::string EncodeBase58(const unsigned char*, const unsigned char*)’:
Base58.cpp:92:5: error: ‘uint32_t’ was not declared in this scope
     uint32_t carry = pbegin[i];
     ^
Base58.cpp:94:7: error: ‘carry’ was not declared in this scope
       carry += (uint32_t)(digits[j]) << 8;
       ^
Base58.cpp:98:11: error: ‘carry’ was not declared in this scope
     while(carry > 0) {
           ^
Makefile:56: recipe for target 'obj/Base58.o' failed
make: *** [obj/Base58.o] Error 1

**Comment by hamnaz** [comment]
i think your are developing and assigning code as per your ubuntu 18 and lib ssl 1.1
we are at ubuntu 16, where these error apear ?

**Comment by JeanLucPons** [comment]
VanitySearch is not using libssl and need a recent compiler (especially for intrinsic functions).
I didn't try with gcc 5.4.0 but I tried with gcc 4.8 and it is not possible to compile VanitySearch with gcc 4.8 due to missing feature of gcc.
It is not possible for you to install the last gcc ?

**Comment by hamnaz** [comment]
gcc 7 +++ available for ubuntu 18 +++
i will try today with gcc 4.8
and will update results here

**Comment by JeanLucPons** [comment]
It won't work with gcc 4.8. As i said VanitySearch use functions not available in gcc 4.8.
I don't know if the needed functions are available in gcc 5.4.0.
The current release can be compiled with gcc 7.3.1 (and gcc 4.8 for nvcc).
https://github.com/JeanLucPons/VanitySearch#linux

**Comment by hamnaz** [comment]
could you pack zip your vanitysearch ubuntu compiled folder and upload , i will download and test, my gpu gtx 460, compute 20 Ok

**Comment by JeanLucPons** [comment]
I uploaded the binary here: http://zelda38.free.fr/VanitySearch
I'm not sure it will work (due to incompatibility with libc installed on your system):
pons@linpons:~/VanitySearch$ ldd ./VanitySearch
	linux-vdso.so.1 (0x00007ffd913e7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb014557000)
	libcudart.so.8.0 => /usr/local/cuda-8.0/lib64/libcudart.so.8.0 (0x00007fb0142f1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb013f68000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb013bca000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb0139b2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb0135c1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb0149df000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb0133bd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb0131b5000)

**Comment by hamnaz** [comment]
its worked :)

chawla@i3-6100:~/van1$ ./VanitySearch -stop -gpu 1Happy
Start Mon Mar 11 21:14:45 2019
Difficulty: 264104224Search: 1Happy
Base Key:6040BEB28A4EF08B04A1DCE6321ECBA38A95731D4EBED3CD26C273593FABCFF5
Number of CPU thread: 1
GPU: GPU #0 GeForce GTX 460 (7x48 cores) Grid(56x128)
51.045 MK/s (GPU 47.704 MK/s) (2^28.08) [P 65.92%][70.00% in 00:00:00][0]
Pub Addr: 1HappyiYwvcit35gFVtenwvJHx8SWh8eYq
Prv Addr: 5K2e78bvsgbhBVEjAji1TGkiZpcsMGZrB7ZXCFesGC9LqxMksim
Prv Key : 0x9FBF414D75B10F74FB5E2319CDE1345B2F9969C945E9CC6E990FEB33908A1051
Check   : 1D7fKNd4fN29ujNufnGvDTUXyiBzCKbGgX
Check   : 1HappyiYwvcit35gFVtenwvJHx8SWh8eYq (comp)

**Comment by JeanLucPons** [comment]
Great. :+1:
