### ISSUE TITLE
Mac OS X Support

### ISSUE THREAD

**Issue by 8eS3rz4sDu8oUx4q39hhv8o2k2e72dkb** [JeanLucPons/VanitySearch#138]
Will it work on macOS 10.15.7+?
I have a lot of problems on first make step
brew and all dep installed. Have anyone got working example? What esle do I need?
I have an AMD Card Radeon RX 5700 XT 8 GB, does it work with CUDA?

```
VanitySearch-master % make
cd obj &&	mkdir -p GPU
cd obj &&	mkdir -p hash
g++ -m64 -mssse3 -Wno-write-strings -O2 -I. -I/usr/local/cuda-8.0/include -o obj/IntGroup.o -c IntGroup.cpp
In file included from IntGroup.cpp:18:
In file included from ./IntGroup.h:21:
./Int.h:241:24: error: static declaration of '__rdtsc' follows non-static
      declaration
static uint64_t inline __rdtsc() {
                       ^
./Int.h:241:24: note: previous implicit declaration is here
1 error generated.
make: *** [obj/IntGroup.o] Error 1
```

**Comment by vladkens** [comment]
Hi. I also had problems running it on macOS, so I created an alternative version (also in pure C):
https://github.com/vladkens/ecloop

This program has fewer features, but take a look, maybe it will work for you.
